[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "llmxsmc"
version = "0.0.1"
authors = [{name = "Sahel Iqbal", email = "sahel13miqbal@proton.me"}]
dependencies = [
  "torch",
  "transformers",
]
